services:
  db:
    image: postgres:15
    container_name: woow_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: woow_backend
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

  # frontend:
  #   build: ./frontend
  #   container_name: woow_frontend
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - "5173:5173"

volumes:
  postgres_data:
